version: "2"

services:

  nats:
    image: nats
    command: -c /container/nats.conf
    volumes:
      - ./nats.conf:/container/nats.conf
    ports:
      - 4222:4222
      - 8222:8222
      - 8090:8090

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: matcher
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
